# The path where generated JSON file is placed.
export_filepath: apps/catalog.json

export_props:
  # The fields included for apps in the generated JSON file.
  - name
  - description
  - license_type
  - disciplines
  - available_on
  - url

listing_order:
  # The literal order of categories on the app index pages. Categories
  # not included (string-valued) and categories with fallback key set to
  # true (mapping-valued) will appear (in undefined order) below the categories
  # listed here.
  #
  # Examples include the license type 'Other' and the 'Miscellaneous'
  # discipline.
  license_types:
    - Free
    - Academic
    - Non-commercial
  disciplines:
    - name: "Biosciences"
      name_fi: "Biotieteet"
    - name: "Chemistry"
      name_fi: "Kemia"
    - name: "Computational Engineering"
      name_fi: "Laskennallinen tekniikka"
    - name: "Data Analytics and Machine Learning"
      name_fi: "Data-analytiikka ja koneoppiminen"
    - name: "Geosciences"
      name_fi: "Geotieteet"
    - name: "Language Research and Other Digital Humanities and Social Sciences"
      name_fi: "Kielten tutkimus sek√§ muut digitaaliset ihmis- ja yhteiskuntatieteet"
    - name: "Mathematics and Statistics"
      name_fi: "Matematiikka ja tilastotiede"
    - name: "Physics"
      name_fi: "Fysiikka"
    - name: "Quantum"
      name_fi: "Kvantti"
    - name: "Miscellaneous"
      name_fi: "Sekalaiset"
      fallback: true
  systems:
    - name: Mahti
      description: "CSC supercomputer for massively parallel jobs"
      description_fi: "CSC:n supertietokone massiiviseen rinnakkaislaskentaan"
    - name: Puhti
      description: "CSC supercomputer for small and medium jobs"
      description_fi: "CSC:n supertietokone jotakinjotakin FIXME"
    - name: LUMI
      description: "EuroHPC supercomputer for CPU and especially GPU jobs"
      description_fi: "EuroHPC:n supertietokone CPU- ja etenkin GPU-laskentaan"

appendix:
  - name: "Chipster"
    description: "Easy-to-use analysis platform for RNA-seq, single cell RNA-seq and other NGS data"
    disciplines:
      - "Biosciences"
    url: "https://chipster.csc.fi/"

  - name: "MaxQuant"
    description: "A proteomics software for processing of Mass-spectromtery data"
    disciplines:
      - "Biosciences"
    src: "support/tutorials/MaxQuant-tutorial.md"

  - name: "eBay's tsv-tools"
    description: "Utilities for manipulating large tabular data files"
    disciplines:
      - "Language Research and Other Digital Humanities and Social Sciences"
    url: "http://urn.fi/urn:nbn:fi:lb-202006081"

  - name: "Finnish Tagtools"
    description: "Finnish Tagtools"
    disciplines:
      - "Language Research and Other Digital Humanities and Social Sciences"
    url: "http://urn.fi/urn:nbn:fi:lb-201908161"

  - name: "finnish-parse"
    description: "Dependency Parser for Finnish"
    disciplines:
      - "Language Research and Other Digital Humanities and Social Sciences"
    url: "http://urn.fi/urn:nbn:fi:lb-2017030801"

  - name: "HFST"
    description: "Helsinki Finite-State Transducer Technology"
    disciplines:
      - "Language Research and Other Digital Humanities and Social Sciences"
    url: "http://urn.fi/urn:nbn:fi:lb-20140730183"

  - name: "HFST-fi"
    description: "Helsinki Finite-State Technology for Finnish"
    disciplines:
      - "Language Research and Other Digital Humanities and Social Sciences"
    url: "http://urn.fi/urn:nbn:fi:lb-201509034"

  - name: "HFST-sv"
    description: "Helsinki Finite-State Technology for Swedish"
    disciplines:
      - "Language Research and Other Digital Humanities and Social Sciences"
    url: "http://urn.fi/urn:nbn:fi:lb-201509035"

  - name: "Kaldi"
    description: "Kaldi Speech Recognition Toolkit"
    disciplines:
      - "Language Research and Other Digital Humanities and Social Sciences"
    url: "http://urn.fi/urn:nbn:fi:lb-2019121020"

  - name: "UDPipe"
    description: "UDPipe Kielipankki version"
    disciplines:
      - "Language Research and Other Digital Humanities and Social Sciences"
    url: "http://urn.fi/urn:nbn:fi:lb-201902131"

  - name: "MySQL"
    description: "MySQL database client"
    disciplines:
      - "Miscellaneous"
    src: "data/kaivos/overview.md"
